name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    name: Build (gerar artefato)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar artefato ZIP
        run: zip -r pipeline-demo.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: codigo-buildado
          path: pipeline-demo.zip